[package]
name = "bfrs"
version = "0.1.0"
authors = ["Dabsunter <dabsunter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#console = "0.7.7"
clap = "2.33.0"
